# Generated by Django 5.2 on 2025-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('powder', 'ProteinPowder'), ('food', 'FoodProduct')], max_length=10)),
                ('product_id', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('total_price', models.FloatField()),
                ('grams', models.IntegerField()),
                ('total_calories', models.IntegerField()),
                ('total_protein', models.FloatField()),
                ('protein_source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinPowder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('total_price', models.FloatField()),
                ('grams', models.IntegerField()),
                ('total_calories', models.IntegerField()),
                ('total_protein', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('trustified', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('powder', 'ProteinPowder'), ('food', 'FoodProduct')], max_length=10)),
                ('product_id', models.IntegerField()),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
            ],
        ),
    ]
