# Generated by Django 5.2 on 2025-04-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pendingsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinpowder',
            name='affiliate_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
